# Config file for automatic testing at travis-ci.org
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
#  - "pypy"  # PyPy not working at present on Travis
#  - "pypy3"

# commands to install dependencies
install:
  - "make -C vendor/liblzf lzf"  # Make the original lzf binary, used in tests
  - "pip install -r requirements.txt -r test-requirements.txt"
  - "python setup.py install"

# command to run tests
script: py.test
